import { docketTheme } from "./theme";
import { typography } from "./typography";

function Row({ children }) {
  return (
    <p
      style={{
        margin: docketTheme.spacing.rowGap + " 0",
        color: docketTheme.colors.text,
      }}
    >
      {children}
    </p>
  );
}

export default function BasicDetailsPreview({ data }) {
  return (
    <div
      style={{
        marginTop: docketTheme.spacing.sectionGap,
        lineHeight: "1.8",
      }}
    >
      {/* LLPS ID + Account Name */}
      <div style={{ display: "flex", margin: "8px 0" }}>
        <div style={{ flex: 1, display: "flex" }}>
          <span style={typography.label}>LLPS ID:</span>
          <span
            style={{
              marginLeft: 5,
              ...typography.value(data.llpsId),
              flex: 1,
              overflow: "hidden",
            }}
          >
            {data.llpsId || "............................................"}
          </span>
        </div>

        <div style={{ flex: 1, display: "flex", marginLeft: 20 }}>
          <span style={typography.label}>A/c Name:</span>
          <span
            style={{
              marginLeft: 5,
              ...typography.value(data.accountName),
              flex: 1,
              overflow: "hidden",
            }}
          >
            {data.accountName ||
              "....................................................................."}
          </span>
        </div>
      </div>

      {/* DOCKET NO + Lead Generated By */}
      <div
        style={{
          display: "flex",
          margin: docketTheme.spacing.rowGap + " 0",
          color: docketTheme.colors.text,
        }}
      >
        {/* DOCKET NO */}
        <div style={{ flex: 1, display: "flex" }}>
          <span style={typography.label}>DOCKET No.:</span>
          <span
            style={{
              marginLeft: 5,
              ...typography.value(data.docketNo),
              overflow: "hidden",
              whiteSpace: "nowrap",
            }}
          >
            {data.docketNo || "..........................................."}
          </span>
        </div>

        {/* LEAD GENERATED BY */}
        <div style={{ flex: 1, display: "flex", marginLeft: 20 }}>
          <span style={typography.label}>Lead Generated By:</span>
          <span
            style={{
              marginLeft: 5,
              ...typography.value(data.leadGeneratedBy),
              overflow: "hidden",
              whiteSpace: "nowrap",
            }}
          >
            {data.leadGeneratedBy || "........................................"}
          </span>
        </div>
      </div>

      {/* Date of Lead + Region + Branch + SOL */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
          gap: "16px",
          margin: "8px 0",
          color: "#333",
        }}
      >
        {[
          { label: "Date of Lead", value: data.dateOfLead },
          { label: "Region", value: data.region },
          { label: "Branch ALPHA", value: data.branchAlpha },
          { label: "SOL ID", value: data.solId },
        ].map((item, idx) => (
          <div key={idx} style={{ minWidth: 0 }}>
            {/* Label */}
            <div style={{ fontWeight: 500, marginBottom: 2 }}>
              {item.label}:
            </div>

            {/* Value line */}
            <div
              style={{
                position: "relative",
                height: "16px",
                lineHeight: "16px",
                overflow: "hidden",
                whiteSpace: "nowrap",
              }}
            >
              {/* Dots background */}
              <span
                style={{
                  position: "absolute",
                  left: 0,
                  right: 0,
                  color: "#999",
                  userSelect: "none",
                }}
              >
                ..............................................
              </span>

              {/* Actual value */}
              <span
                style={{
                  position: "relative",
                  fontWeight: item.value ? "bold" : "normal",
                  backgroundColor: "#fff",
                  paddingRight: "4px",
                }}
              >
                {item.value || ""}
              </span>
            </div>
          </div>
        ))}
      </div>

      {/* Contact Numbers */}
      <Row>
        <span style={typography.label}>Contact No of Customer:</span>{" "}
        <span style={typography.value(data.customerContact)}>
          {data.customerContact ||
            "......................................................"}
        </span>
        <span style={{ marginLeft: 10, ...typography.label }}>
          Contact No. of Branch:
        </span>{" "}
        <span style={typography.value(data.branchContact)}>
          {data.branchContact ||
            "..................................................."}
        </span>
      </Row>

      {/* Loan Facility */}
      <Row>
        <span style={typography.label}>Loan Facility:</span>{" "}
        <span style={typography.value(data.loanFacility)}>
          {data.loanFacility || "........"}
        </span>
        <span style={{ marginLeft: 5 }}>
          {data.loanFacility
            ? "Baroda Gyan / Premier Institution / EDP / SCHOLAR / Scholar EDP / Vidya"
            : ".................... Baroda Gyan / Premier Institution / EDP / SCHOLAR / Scholar EDP / Vidya"}
        </span>
      </Row>

      {/* Loan Amount + Course Fees + Eligibility + Insurance */}
      <Row>
        <span style={typography.label}>Loan Amount:</span>{" "}
        <span style={typography.value(data.loanAmount)}>
          {data.loanAmount || "............../.-"}
        </span>
        <span style={{ marginLeft: 10, ...typography.label }}>
          Course Fees:
        </span>{" "}
        <span style={typography.value(data.courseFees)}>
          {data.courseFees || "...................."}
        </span>
        <span style={{ marginLeft: 10, ...typography.label }}>
          Eligibility:
        </span>{" "}
        <span style={typography.value(data.eligibility)}>
          {data.eligibility || "............................."}
        </span>
        <span style={{ marginLeft: 10, ...typography.label }}>Insurance:</span>{" "}
        <span style={typography.value(data.insurance)}>
          {data.insurance || "..................."}
        </span>
        <span>.</span>
      </Row>

      {/* Deviation */}
      <Row>
        <span style={typography.label}>Any Deviation required</span>{" "}
        <span style={typography.value(data.deviation)}>
          {data.deviation ||
            "..........................................................................................................................................................."}
        </span>
      </Row>
    </div>
  );
}
