import CourseDetailsPreview from "./CourseDetailsPreview";

export default function DocketPreview({ headerData, basicData, courseData }) {
  return (
    <div
      style={{
        width: "794px", // ✅ A4 width in PX
        minHeight: "1123px", // ✅ A4 height in PX
        padding: "38px", // ≈ 10mm
        backgroundColor: "#fff",
        boxShadow: "0 0 10px rgba(0,0,0,0.1)",
        fontFamily: "Times New Roman, serif",
        fontSize: "12px",
        boxSizing: "border-box",
        overflow: "hidden",
      }}
    >
      {/* Document Header */}
      <h1
        style={{
          textAlign: "center",
          fontSize: "20px",
          fontWeight: "bold",
          margin: "0 0 10px 0",
          color: "#808080",
        }}
      >
        {headerData.title} ({headerData.academicYear})
      </h1>

      <h2
        style={{
          textAlign: "center",
          fontSize: "14px",
          fontWeight: "bold",
          margin: "0 0 20px 0",
          color: "#808080",
        }}
      >
        {headerData.subtitle}
      </h2>

      {/* Basic Details Section */}
      <div style={{ marginTop: "20px", fontSize: "12px", lineHeight: "1.8" }}>
        <div style={{ display: "flex", margin: "8px 0", color: "#333" }}>
          <div style={{ flex: 1, display: "flex" }}>
            <span style={{ fontWeight: "500" }}>LLPS ID:</span>
            <span
              style={{
                marginLeft: "5px",
                fontWeight: basicData.llpsId ? "bold" : "normal",
                flex: 1,
                overflow: "hidden",
              }}
            >
              {basicData.llpsId ||
                "............................................"}
            </span>
          </div>
          <div style={{ flex: 2, display: "flex", marginLeft: "20px" }}>
            <span style={{ fontWeight: "500" }}>A/c Name:</span>
            <span
              style={{
                marginLeft: "5px",
                fontWeight: basicData.accountName ? "bold" : "normal",
                flex: 1,
                overflow: "hidden",
              }}
            >
              {basicData.accountName ||
                "....................................................................."}
            </span>
          </div>
        </div>

        <p style={{ margin: "8px 0", color: "#333" }}>
          <span style={{ fontWeight: "500", width: "200mm" }}>DOCKET No.:</span>
          <span
            style={{
              marginLeft: "5px",
              fontWeight: basicData.docketNo ? "bold" : "normal",
            }}
          >
            {basicData.docketNo ||
              "..........................................."}
          </span>
          <span
            style={{ marginLeft: "10px", fontWeight: "500", width: "200mm" }}
          >
            Lead Generated By:
          </span>
          <span
            style={{
              marginLeft: "5px",
              fontWeight: basicData.leadGeneratedBy ? "bold" : "normal",
            }}
          >
            {basicData.leadGeneratedBy ||
              "........................................"}
          </span>
        </p>

        <p style={{ margin: "8px 0", color: "#333" }}>
          <span style={{ fontWeight: "500", width: "200mm" }}>
            Date of Lead:
          </span>
          <span
            style={{
              marginLeft: "5px",
              fontWeight: basicData.dateOfLead ? "bold" : "normal",
            }}
          >
            {basicData.dateOfLead || "..................................."}
          </span>
          <span
            style={{ marginLeft: "10px", fontWeight: "500", width: "200mm" }}
          >
            Region:
          </span>
          <span
            style={{
              marginLeft: "5px",
              fontWeight: basicData.region ? "bold" : "normal",
            }}
          >
            {basicData.region || "......"}
          </span>
          <span
            style={{ marginLeft: "10px", fontWeight: "500", width: "200mm" }}
          >
            Branch ALPHA:
          </span>
          <span
            style={{
              marginLeft: "5px",
              fontWeight: basicData.branchAlpha ? "bold" : "normal",
            }}
          >
            {basicData.branchAlpha || "......"}
          </span>
          <span
            style={{ marginLeft: "10px", fontWeight: "500", width: "200mm" }}
          >
            SOL ID:
          </span>
          <span
            style={{
              marginLeft: "5px",
              fontWeight: basicData.solId ? "bold" : "normal",
            }}
          >
            {basicData.solId || "............................."}
          </span>
        </p>

        <p style={{ margin: "8px 0", color: "#333" }}>
          <span style={{ fontWeight: "500", width: "200mm" }}>
            Contact No of Customer:
          </span>
          <span
            style={{
              marginLeft: "5px",
              fontWeight: basicData.customerContact ? "bold" : "normal",
            }}
          >
            {basicData.customerContact ||
              "......................................................"}
          </span>
          <span
            style={{ marginLeft: "10px", fontWeight: "500", width: "200mm" }}
          >
            Contact No. of Branch:
          </span>
          <span
            style={{
              marginLeft: "5px",
              fontWeight: basicData.branchContact ? "bold" : "normal",
            }}
          >
            {basicData.branchContact ||
              "..................................................."}
          </span>
        </p>

        <p style={{ margin: "8px 0", color: "#333" }}>
          <span style={{ fontWeight: "500", width: "200mm" }}>
            Loan Facility:
          </span>
          <span
            style={{
              marginLeft: "5px",
              fontWeight: basicData.loanFacility ? "bold" : "normal",
            }}
          >
            {basicData.loanFacility || "........"}
          </span>
          <span style={{ marginLeft: "5px", width: "200mm" }}>
            {basicData.loanFacility
              ? "Baroda Gyan / Premier Institution / EDP / SCHOLAR / Scholar EDP / Vidya"
              : ".................... Baroda Gyan / Premier Institution / EDP / SCHOLAR / Scholar EDP / Vidya"}
          </span>
        </p>

        <p style={{ margin: "8px 0", color: "#333" }}>
          <span style={{ fontWeight: "500", width: "200mm" }}>
            Loan Amount:
          </span>
          <span
            style={{
              marginLeft: "5px",
              fontWeight: basicData.loanAmount ? "bold" : "normal",
            }}
          >
            {basicData.loanAmount || "............../.-"}
          </span>
          <span
            style={{ marginLeft: "10px", fontWeight: "500", width: "200mm" }}
          >
            Course Fees:
          </span>
          <span
            style={{
              marginLeft: "5px",
              fontWeight: basicData.courseFees ? "bold" : "normal",
            }}
          >
            {basicData.courseFees || "...................."}
          </span>
          <span
            style={{ marginLeft: "10px", fontWeight: "500", width: "200mm" }}
          >
            Eligibility
          </span>
          <span
            style={{
              marginLeft: "5px",
              fontWeight: basicData.eligibility ? "bold" : "normal",
            }}
          >
            {basicData.eligibility || "............................."}
          </span>
          <span
            style={{ marginLeft: "10px", fontWeight: "500", width: "200mm" }}
          >
            Insurance :
          </span>
          <span
            style={{
              marginLeft: "5px",
              fontWeight: basicData.insurance ? "bold" : "normal",
            }}
          >
            {basicData.insurance || "..................."}
          </span>
          <span style={{ marginLeft: "5px", width: "200mm" }}>.</span>
        </p>

        <p style={{ margin: "8px 0", color: "#333" }}>
          <span style={{ fontWeight: "500", width: "200mm" }}>
            Any Deviation required
          </span>
          <span
            style={{
              marginLeft: "5px",
              fontWeight: basicData.deviation ? "bold" : "normal",
            }}
          >
            {basicData.deviation ||
              "..........................................................................................................................................................."}
          </span>
        </p>
      </div>
      {/* COURSE DETAILS SECTION */}
      <CourseDetailsPreview data={courseData} />
    </div>
  );
}
