export default function BasicDetailsForm({ data, onChange }) {
  const inputStyle = {
    width: "100%",
    padding: "10px",
    border: "1px solid #ddd",
    borderRadius: "4px",
    fontSize: "14px",
    boxSizing: "border-box"
  };

  const labelStyle = {
    display: "block",
    marginBottom: "5px",
    fontWeight: "500",
    fontSize: "14px"
  };

  return (
    <div style={{ marginBottom: "20px" }}>
      <h2 style={{ fontSize: "18px", marginBottom: "15px", color: "#333" }}>
        Basic Details
      </h2>
      
      {/* LLPS ID and Account Name in one row */}
      <div style={{ display: "flex", gap: "15px", marginBottom: "15px" }}>
        <div style={{ flex: 1 }}>
          <label style={labelStyle}>LLPS ID</label>
          <input
            type="text"
            value={data.llpsId}
            onChange={(e) => onChange("llpsId", e.target.value)}
            placeholder="e.g., 3796201"
            style={inputStyle}
          />
        </div>

        <div style={{ flex: 1 }}>
          <label style={labelStyle}>Account Name</label>
          <input
            type="text"
            value={data.accountName}
            onChange={(e) => onChange("accountName", e.target.value)}
            placeholder="e.g., Vishwas Shukla"
            style={inputStyle}
          />
        </div>
      </div>

      {/* Docket No and Lead Generated By in one row */}
      <div style={{ display: "flex", gap: "15px", marginBottom: "15px" }}>
        <div style={{ flex: 1 }}>
          <label style={labelStyle}>Docket No.</label>
          <input
            type="text"
            value={data.docketNo}
            onChange={(e) => onChange("docketNo", e.target.value)}
            placeholder="Docket Number"
            style={inputStyle}
          />
        </div>

        <div style={{ flex: 1 }}>
          <label style={labelStyle}>Lead Generated By</label>
          <input
            type="text"
            value={data.leadGeneratedBy}
            onChange={(e) => onChange("leadGeneratedBy", e.target.value)}
            placeholder="e.g., BGSS (Rupendra Singh)"
            style={inputStyle}
          />
        </div>
      </div>

      {/* Date of Lead and Region in one row */}
      <div style={{ display: "flex", gap: "15px", marginBottom: "15px" }}>
        <div style={{ flex: 1 }}>
          <label style={labelStyle}>Date of Lead</label>
          <input
            type="text"
            value={data.dateOfLead}
            onChange={(e) => onChange("dateOfLead", e.target.value)}
            placeholder="DD-MM-YYYY"
            style={inputStyle}
          />
        </div>

        <div style={{ flex: 1 }}>
          <label style={labelStyle}>Region</label>
          <input
            type="text"
            value={data.region}
            onChange={(e) => onChange("region", e.target.value)}
            placeholder="e.g., North"
            style={inputStyle}
          />
        </div>
      </div>

      {/* Branch ALPHA and SOL ID in one row */}
      <div style={{ display: "flex", gap: "15px", marginBottom: "15px" }}>
        <div style={{ flex: 1 }}>
          <label style={labelStyle}>Branch ALPHA</label>
          <input
            type="text"
            value={data.branchAlpha}
            onChange={(e) => onChange("branchAlpha", e.target.value)}
            placeholder="e.g., VJSAME"
            style={inputStyle}
          />
        </div>

        <div style={{ flex: 1 }}>
          <label style={labelStyle}>SOL ID</label>
          <input
            type="text"
            value={data.solId}
            onChange={(e) => onChange("solId", e.target.value)}
            placeholder="SOL ID"
            style={inputStyle}
          />
        </div>
      </div>

      {/* Contact Numbers in one row */}
      <div style={{ display: "flex", gap: "15px", marginBottom: "15px" }}>
        <div style={{ flex: 1 }}>
          <label style={labelStyle}>Contact No of Customer</label>
          <input
            type="text"
            value={data.customerContact}
            onChange={(e) => onChange("customerContact", e.target.value)}
            placeholder="Customer Contact Number"
            style={inputStyle}
          />
        </div>

        <div style={{ flex: 1 }}>
          <label style={labelStyle}>Contact No. of Branch</label>
          <input
            type="text"
            value={data.branchContact}
            onChange={(e) => onChange("branchContact", e.target.value)}
            placeholder="Branch Contact Number"
            style={inputStyle}
          />
        </div>
      </div>

      {/* Loan Facility - full width */}
      <div style={{ marginBottom: "15px" }}>
        <label style={labelStyle}>Loan Facility</label>
        <input
          type="text"
          value={data.loanFacility}
          onChange={(e) => onChange("loanFacility", e.target.value)}
          placeholder="e.g., Baroda Gyan"
          style={inputStyle}
        />
      </div>

      {/* Loan Amount and Course Fees in one row */}
      <div style={{ display: "flex", gap: "15px", marginBottom: "15px" }}>
        <div style={{ flex: 1 }}>
          <label style={labelStyle}>Loan Amount</label>
          <input
            type="text"
            value={data.loanAmount}
            onChange={(e) => onChange("loanAmount", e.target.value)}
            placeholder="Loan Amount"
            style={inputStyle}
          />
        </div>

        <div style={{ flex: 1 }}>
          <label style={labelStyle}>Course Fees</label>
          <input
            type="text"
            value={data.courseFees}
            onChange={(e) => onChange("courseFees", e.target.value)}
            placeholder="Course Fees"
            style={inputStyle}
          />
        </div>
      </div>

      {/* Eligibility and Insurance in one row */}
      <div style={{ display: "flex", gap: "15px", marginBottom: "15px" }}>
        <div style={{ flex: 1 }}>
          <label style={labelStyle}>Eligibility</label>
          <input
            type="text"
            value={data.eligibility}
            onChange={(e) => onChange("eligibility", e.target.value)}
            placeholder="Eligibility"
            style={inputStyle}
          />
        </div>

        <div style={{ flex: 1 }}>
          <label style={labelStyle}>Insurance</label>
          <input
            type="text"
            value={data.insurance}
            onChange={(e) => onChange("insurance", e.target.value)}
            placeholder="Insurance"
            style={inputStyle}
          />
        </div>
      </div>

      {/* Deviation - full width */}
      <div style={{ marginBottom: "15px" }}>
        <label style={labelStyle}>Any Deviation Required</label>
        <input
          type="text"
          value={data.deviation}
          onChange={(e) => onChange("deviation", e.target.value)}
          placeholder="Deviation details"
          style={inputStyle}
        />
      </div>
    </div>
  );
}

